/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cegal.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8711532963300963904L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerAddress\",\"namespace\":\"com.cegal.avro.model\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"street\",\"type\":\"string\"},{\"name\":\"postcode\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerAddress> ENCODER =
      new BinaryMessageEncoder<CustomerAddress>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerAddress> DECODER =
      new BinaryMessageDecoder<CustomerAddress>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerAddress> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerAddress>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerAddress to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerAddress from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerAddress instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence name;
   private java.lang.CharSequence street;
   private java.lang.CharSequence postcode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerAddress() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param street The new value for street
   * @param postcode The new value for postcode
   */
  public CustomerAddress(java.lang.CharSequence name, java.lang.CharSequence street, java.lang.CharSequence postcode) {
    this.name = name;
    this.street = street;
    this.postcode = postcode;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return street;
    case 2: return postcode;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: street = (java.lang.CharSequence)value$; break;
    case 2: postcode = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'street' field.
   * @return The value of the 'street' field.
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }


  /**
   * Sets the value of the 'street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'postcode' field.
   * @return The value of the 'postcode' field.
   */
  public java.lang.CharSequence getPostcode() {
    return postcode;
  }


  /**
   * Sets the value of the 'postcode' field.
   * @param value the value to set.
   */
  public void setPostcode(java.lang.CharSequence value) {
    this.postcode = value;
  }

  /**
   * Creates a new CustomerAddress RecordBuilder.
   * @return A new CustomerAddress RecordBuilder
   */
  public static com.cegal.avro.model.CustomerAddress.Builder newBuilder() {
    return new com.cegal.avro.model.CustomerAddress.Builder();
  }

  /**
   * Creates a new CustomerAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerAddress RecordBuilder
   */
  public static com.cegal.avro.model.CustomerAddress.Builder newBuilder(com.cegal.avro.model.CustomerAddress.Builder other) {
    if (other == null) {
      return new com.cegal.avro.model.CustomerAddress.Builder();
    } else {
      return new com.cegal.avro.model.CustomerAddress.Builder(other);
    }
  }

  /**
   * Creates a new CustomerAddress RecordBuilder by copying an existing CustomerAddress instance.
   * @param other The existing instance to copy.
   * @return A new CustomerAddress RecordBuilder
   */
  public static com.cegal.avro.model.CustomerAddress.Builder newBuilder(com.cegal.avro.model.CustomerAddress other) {
    if (other == null) {
      return new com.cegal.avro.model.CustomerAddress.Builder();
    } else {
      return new com.cegal.avro.model.CustomerAddress.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerAddress instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerAddress>
    implements org.apache.avro.data.RecordBuilder<CustomerAddress> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence street;
    private java.lang.CharSequence postcode;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cegal.avro.model.CustomerAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.street)) {
        this.street = data().deepCopy(fields()[1].schema(), other.street);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.postcode)) {
        this.postcode = data().deepCopy(fields()[2].schema(), other.postcode);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cegal.avro.model.CustomerAddress other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.street)) {
        this.street = data().deepCopy(fields()[1].schema(), other.street);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.postcode)) {
        this.postcode = data().deepCopy(fields()[2].schema(), other.postcode);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.cegal.avro.model.CustomerAddress.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.cegal.avro.model.CustomerAddress.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }


    /**
      * Sets the value of the 'street' field.
      * @param value The value of 'street'.
      * @return This builder.
      */
    public com.cegal.avro.model.CustomerAddress.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.street = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'street' field.
      * @return This builder.
      */
    public com.cegal.avro.model.CustomerAddress.Builder clearStreet() {
      street = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'postcode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostcode() {
      return postcode;
    }


    /**
      * Sets the value of the 'postcode' field.
      * @param value The value of 'postcode'.
      * @return This builder.
      */
    public com.cegal.avro.model.CustomerAddress.Builder setPostcode(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.postcode = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'postcode' field has been set.
      * @return True if the 'postcode' field has been set, false otherwise.
      */
    public boolean hasPostcode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'postcode' field.
      * @return This builder.
      */
    public com.cegal.avro.model.CustomerAddress.Builder clearPostcode() {
      postcode = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerAddress build() {
      try {
        CustomerAddress record = new CustomerAddress();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.street = fieldSetFlags()[1] ? this.street : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.postcode = fieldSetFlags()[2] ? this.postcode : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerAddress>
    READER$ = (org.apache.avro.io.DatumReader<CustomerAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.street);

    out.writeString(this.postcode);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);

      this.postcode = in.readString(this.postcode instanceof Utf8 ? (Utf8)this.postcode : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.street = in.readString(this.street instanceof Utf8 ? (Utf8)this.street : null);
          break;

        case 2:
          this.postcode = in.readString(this.postcode instanceof Utf8 ? (Utf8)this.postcode : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










